"""
Represents text resources that serve as evidence for historical or conceptual
relationships.

.. autosummary::

   Text
"""   

from django.db import models

class Text(models.Model):
    """
    Represents a text resource that serves as evidence for historical or conceptual relationships.
    
    Instances of :class:`.Text` can be generated by direct upload via the
    admin interface, or retrieved from a :class:`.Repository`\.
    
    Attributes
    ----------
    uri : str
        The text's URI.
    filename : str
        The original filename for the text object.
    title : str
        The human-readable title of the text.
    dateCreated : datetime
        The datetime when the original text was created, e.g. publication date.
    dateDigitized : datetime
        The datetime when the text was converted to a digital resource.
    dateAdded : datetime
        The datetime when the text was added to the Genecology Project webapp.
    dateModified : datetime
        The datetime when the last change was made to the text.
    creator :
        ManyToMany reference to :class:`.Concept`\, which represent the original
        creators (e.g. authors) of the text.
    content : str
        The content of the text itself.
    length : str
        The number of characters (including spaces) in the text.
    restricted : bool
        If ``True``, unauthenticated users may not view the full ``content`` of
        the text.
    """
    uri = models.CharField(max_length=500, unique=True)
    filename = models.CharField(max_length=200, blank=True, null=True)
    title = models.CharField(max_length=500)
    
    dateCreated = models.DateField()
    dateDigitized = models.DateField()
    dateAdded = models.DateField(auto_now_add=True)
    dateModified = models.DateField(auto_now=True)

    creator = models.ManyToManyField('concepts.Concept') # Presumably a person.

    content = models.TextField()
    length = models.IntegerField(default=0)
    
    restricted = models.BooleanField(default=True)
    
    class Meta:
        verbose_name_plural = "texts"
